- name: "Install developer tools"
  become: yes
  apt: name={{ item }}
  with_items:
    - git
    - gitg
    - tig
    - meld
    - nmap
  when: ansible_distribution == 'Ubuntu'
 
- name: "Install ipython"
  become: yes
  pip: name='ipython[all]'
