- hosts: all
  vars:
      workspace: "{{ ansible_env.HOME }}/workspace"
  roles:
      - { role: base, tags: ['base'] }
      - { role: developer, tags: ['developer'] }
      - { role: vim, tags: ['vim'] }
      - { role: desktop, tags: ['desktop'] }
