- name: "Create directory {{ ansible_env.HOME}}/.fonts"
  file: path={{ ansible_env.HOME }}/.fonts state=directory mode=0755 owner={{ansible_user}} group={{ ansible_user }}

- name: "Clone repo Fira font"
  git: repo=https://github.com/mozilla/Fira.git dest={{ workspace }}/pkg/Fira
  register: fira

- name: "Install Fira font"
  copy: src={{ workspace }}/pkg/Fira/ttf/ dest=/home/{{ ansible_user }}/.fonts
  when: fira.changed

- name: "Set mono space font"
  shell: gsettings set org.gnome.desktop.interface monospace-font-name 'Fira Mono Regular 14'
  ignore_errors: yes

- name: "Install applications"
  become: yes
  apt: name={{ item }}
  with_items:
    - corebird
    - vlc
    - tmux
