- name: "Create directory {{ ansible_env.HOME}}/.fonts"
  file: path={{ ansible_env.HOME }}/.fonts state=directory mode=0755 owner={{ansible_user}} group={{ ansible_user }}

- name: "Clone repo Fira font"
  git: repo=https://github.com/mozilla/Fira.git dest={{ workspace }}/pkg/Fira
  register: fira

- name: "Install Fira font"
  copy: src={{ workspace }}/pkg/Fira/ttf/ dest=/home/{{ ansible_user }}/.fonts
  when: fira.changed

- name: "Set mono space font"
  shell: gsettings set org.gnome.desktop.interface monospace-font-name 'Fira Mono Regular 14'
  ignore_errors: yes

- name: "Add Spotify repository signing key"      
  become: yes
  apt_key: keyserver=keyserver.ubuntu.com id=BBEBDCB318AD50EC6865090613B00F1FD2C19886

- name: "Add Spotify repository"      
  become: yes
  apt_repository: repo='deb http://repository.spotify.com stable non-free' state=present

 
- name: "Add Google chrome repository signing key"      
  become: yes
  apt_key: keyserver=keyserver.ubuntu.com id=D38B4796

- name: "Add google chrome repository"
  become: yes
  apt_repository: repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' state=present
 
- name: "Install applications"
  become: yes
  apt: name={{ item }}
  with_items:
    - vlc
    - tmux
    - google-chrome-stable
    - spotify-client

- name: "Enable unity workspaces"
  shell: gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ {{ item }}
  with_items:
    - hsize 4
    - vsize 1

