---
- name: "Create a directory if it does not exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ ansible_env.HOME }}/.config/i3"
    - "{{ ansible_env.HOME }}/.config/i3status"
    - "{{ ansible_env.HOME }}/.local/share/fonts/"

- name: "Installing Nerd Font"
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hack.zip
    remote_src: yes
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/"
  register: fonts

- name: "Update font chache"
  shell: fc-cache -fv
  when: fonts.changed

- name: "Deploy .config/alacritty/alacritty.yml"
  ansible.builtin.template: src=alacritty.yml.j2 dest={{ ansible_env.HOME}}/.alacritty.yml

- name: "Deploy .bashrc"
  ansible.builtin.copy: src=bashrc dest={{ ansible_env.HOME}}/.bashrc

- name: "Deploy .rcrc"
  ansible.builtin.copy: src=rcrc dest={{ ansible_env.HOME}}/.rcrc

- name: "Deploy .tmux.conf"
  ansible.builtin.copy: src=tmux dest={{ ansible_env.HOME}}/.tmux.conf

- name: "Deploy .Xresources"
  ansible.builtin.template: src=Xresources.j2 dest={{ ansible_env.HOME}}/.Xresources
  register: xresources

- name: "Update Xresources"
  ansible.builtin.shell: |
    xrdb -merge "{{ ansible_env.HOME}}/.Xresources"
  when: xresources.changed

- name: "Deploy .config/i3/config"
  ansible.builtin.template: src=i3.j2 dest={{ ansible_env.HOME}}/.config/i3/config
  register: i3config

- name: "Deploy .config/i3status/config"
  ansible.builtin.copy: src=i3status dest={{ ansible_env.HOME}}/.config/i3status/config
  register: i3status

- name: "Restart i3"
  ansible.builtin.shell: |
    i3 status && i3 restart
  when: i3config.changed or i3status.changed
